tm/mv script solve cold migration only here
Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

diff --git a/tm/3par/mv b/tm/3par/mv
--- a/tm/3par/mv
+++ b/tm/3par/mv
@@ -72,22 +72,15 @@ if [ "$SRC" == "$DST" ]; then
     exit 0
 fi
 
-# VM is in unknown state, SRC_HOST probably in failed state
-# Run pre/post migrate only if dest path is not disk
 LCM_STATE=`lcm_state`
-if [ $LCM_STATE -eq 60 ] || [ $LCM_STATE -eq 61 ]; then
-  if [ `is_disk $DST_PATH` -eq 0 ]; then
-    TEMPLATE=$(onevm show -x "$VMID" | base64 -w0)
-
-    echo "${TEMPLATE}" | `dirname $0`/premigrate ${SRC_HOST} ${DST_HOST} ${DST_PATH} ${VMID} ${DSID}
-    echo "${TEMPLATE}" | `dirname $0`/postmigrate ${SRC_HOST} ${DST_HOST} ${DST_PATH} ${VMID} ${DSID}
-  fi
-
-  log "Not moving files from $SRC_HOST in FT mode"
-  exit 0
-fi
 
 if [ `is_disk $DST_PATH` -eq 0 ]; then
+    # VM is in unknown state, SRC_HOST probably in failed state
+    if [ $LCM_STATE -eq 60 ] || [ $LCM_STATE -eq 61 ]; then
+      log "Not moving files from $SRC_HOST in FT mode"
+      exit 0
+    fi
+
     ssh_make_path "$DST_HOST" "$DST_DIR"
 
     log "Moving $SRC to $DST"
@@ -197,16 +190,19 @@ if [ "$PERSISTENT" != "YES" ] && [ "$CLONE" == "NO" ]; then
 fi
 
 if [ "$SRC_HOST_3PAR" == "1" ] && [ "$CAN_UNMAP" == "1" ]; then
-    FLUSH_CMD=$(cat <<EOF
-        set -e
-        $(remove_lun "$WWN")
+    log "Unmapping $WWN from $SRC_HOST"
+
+    # src host in failed state, can not flush disk before unexport
+    if [ $LCM_STATE -ne 60 ] && [ $LCM_STATE -ne 61 ]; then
+        FLUSH_CMD=$(cat <<EOF
+          set -e
+          $(remove_lun "$WWN")
 EOF
 )
 
-    log "Unmapping $WWN from $SRC_HOST"
-
-    ssh_exec_and_log "$SRC_HOST" "$FLUSH_CMD" \
-        "Error flushing out mapping"
+        ssh_exec_and_log "$SRC_HOST" "$FLUSH_CMD" \
+            "Error flushing out mapping"
+    fi
 
     python ${DRIVER_PATH}/../../datastore/3par/3par.py unexportVV -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME -p $PASSWORD \
                                                                 -n $NAME -hs $SRC_HOST
