Reworked TM MV if VM is in unknow state
This reverts commit c18c296a4d67906e7708c6cabdd1efedc6fa6fb8.

Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

diff --git a/tm/3par/postmigrate b/tm/3par/postmigrate
--- a/tm/3par/postmigrate
+++ b/tm/3par/postmigrate
@@ -141,16 +141,20 @@ for j in `seq 1 ${#DISK_IDS[*]}`; do
         NAME=$(get_vv_name "$NAME_WWN")
         WWN=$(get_vv_wwn "$NAME_WWN")
 
-        FLUSH_CMD=$(cat <<EOF
-              set -e
-              $(remove_lun "$WWN")
+        # Don't unmap if VM is in unknown state
+        # just unexport, SRC_HOST is probably in failed state
+        if [ `lcm_state` -ne 60 ]; then
+          FLUSH_CMD=$(cat <<EOF
+                set -e
+                $(remove_lun "$WWN")
 EOF
 )
 
-        log "Unmapping $NAME_WWN from $SRC_HOST"
+          log "Unmapping $NAME_WWN from $SRC_HOST"
 
-        ssh_exec_and_log "$SRC_HOST" "$FLUSH_CMD" \
-            "Error flushing out mapping"
+          ssh_exec_and_log "$SRC_HOST" "$FLUSH_CMD" \
+              "Error flushing out mapping"
+        fi
 
         python ${DRIVER_PATH}/../../datastore/3par/3par.py unexportVV -a $API_ENDPOINT -i $IP -s $SECURE -u $USERNAME \
                                                                                  -p $PASSWORD -n $NAME -hs $SRC_HOST
@@ -164,6 +168,10 @@ done
 
 migrate_other "$@"
 
-exec_and_log "$SSH $SRC_HOST rm -rf $DST_PATH"
+# Don't perform cleanup if VM is in unknown state
+# SRC_HOST is probably in failed state
+if [ `lcm_state` -ne 60 ]; then
+  exec_and_log "$SSH $SRC_HOST rm -rf $DST_PATH"
+fi
 
 exit 0
